python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\05pV1Zy1lBk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\0hQ_WAXmbz8.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\0t8lCdG0dV4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\0Vg-BRYfBJQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\2-aeLm1r1mY.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\2hKd98-LBcc.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\2PrbtQMLUyc.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\2pZgnaRq9eU.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\2XwpPx--TEc.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\3XXPXKpv5U4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\3ykoLzbulpw.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\4Ym9T3UBYzc.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\7HVK_Q4DnJs.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\7JI0zSLq_xw.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\85WgO428JVI.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\8I33FkCLiSQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\94Kz-_yc1as.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\9aHLmSWcyWc.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\9mu60_leQQY.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\aecnWEbm3Zg.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\ahjUOTaEFGA.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Ajz-iylNBDw.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\aQ8ACsk14tQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\aV1NNKGvYoY.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\aWoE3QZ_PW4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\b1Lbhlb8290.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\bnaXvm5NlGk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\bPheznNe3P8.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\bv6fypgX0Pg.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\bz-H8Rq3UQk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\cgvQ80EtFOw.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Db0W2x5f44U.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\ddsl46PBq08.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\dhf4qwXdeN4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\DTrPC984Qyc.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\DUd1clEHYy4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\DuIfez3Vf6c.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\EiAHVk9wlMA.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\FH35NRbiG3g.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\fHcEfsuPLlU.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\fieZETwnAwY.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\fITZfWXwxv4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\FKNgAZNBqcI.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\FptKWS7yB18.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\FQEp2NJnfzE.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\FVe-87qMFzM.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\g8GASxnz9V0.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\g9r4l5KveSs.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\GBPRwDSgqyI.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\GDGdpbGvKFE.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\GGYVavOr5BU.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\HgbvDIXDeD4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\hlWMM1_AvK4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\HUyrSBs6KRk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\ICBFRqZ8zxs.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\iHZnaGldXkk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\ikKUUDZ0QJk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\INQ5xUHwDZA.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\iopeUvrYX9Q.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\IQZzc0oQsFk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\iUK6fTw948E.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\jK7MU4a69fo.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\J_MamX_v_Zg.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\k-jUagYDCt0.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\kB7lNkyZbYU.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\KfuCKrCfano.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Kg0jPX1d5P8.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\KGqcHhCeOKA.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\KJFObIJk9FY.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\KM1SR_DJjhY.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\l8J77LYeWxU.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\L99bKn2a5rI.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\LFHwqQno29c.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Mf5dqtllvSE.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\MI36h7Fgfus.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\mnDx0OXHx5s.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\mONstSZgMLw.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\mxjfmy1rJv4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\m_Kxzv06XJ8.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\NEKqx_l-8gk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\nh3tyMBg8zk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\nJNDQzoToTQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\N_PJTS70XNA.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\ObCDvnTYlLQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\OM5dkPyN1XY.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\ORC0fPplTT4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\OvPqu6H2hUM.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\O_5f10m1n_o.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\PA_n8C9QgQk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\pQavdTKGDvM.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\pwo_mcwKXTA.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\q0PF_jRy4kQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\q4ut-4QWuGM.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\qRxZZ7yDmMU.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\q_E8TT4mm6A.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\R4FRyQJChbM.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\riMh8QwHwsI.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\rLiFc4HfRjw.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\rMwP0diw9vM.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\RyWuy_OA288.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\S3Bx5l0PX1Q.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\sfonUm4ZPDw.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\SgeT1NJfYaU.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Sj2doQ_LP3M.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Tc04EBhH7D4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\ToH14OiFhnI.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\touL_nKxp5A.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\TpCeUyy6264.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\TYaGHxgBIPo.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\UA40uWi6a1w.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\UBllW_0N53k.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\UM8CN2QX--A.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\UOBICnW9lCU.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Ux8bI98b08Q.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\vDgWIgTzu78.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\VivtJ6lCv1g.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\vmPxfpTODEQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\W0SvU3AuChk.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\WfiC1cyTG-k.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\wgZO-VcRiKM.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\wzUfUaAV_pQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\xcldn8Fpx1Y.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Y6tDkrxOXr8.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\yD7Qhc17pD0.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\yFZWqY7Cvx4.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\YhNfH11KVJ8.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\yKuA8koweIg.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\YmqiWrn0g3k.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\yPr8p9PD634.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\YvtJ_7TF7uM.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\YxStSmMWwEQ.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Z40I_I7yQ0A.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\z7AAYK_a858.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\zGAD7HrJlEc.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Zn98CE-R_0Q.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\ZoVMvHkH5iI.json
python C:\Users\emzou\somen\sorry.py -f C:\Users\emzou\somen\jason\Zwc6lK_LQ7E.json